[package]
name = "imager"
version = "0.1.0"
authors = ["Colbyn Wadman <hello@colbyn.com>"]
edition = "2018"
publish = false

[dependencies]
imager = "0.0.6"
glob = "^0.3"
clap = "^2.33"
structopt = "^0.2"
rayon = "1.1.0"
either = {version = "^1", features = ["serde"]}
serde = {version = "^1.0", features = ["derive"]}
serde_json = "^1.0"
tempfile = "3.1.0"
lazy_static = "1.4.0"
itertools = "0.8.0"
indicatif = "0.12.0"
